### ISSUE TITLE
Will Re:PhiEditor be supported?

### ISSUE THREAD

**Issue by Shikochin** [Mivik/prpr#2]
As the title suggests.

**Comment by Mivik** [comment]
Re:Phiedit is supported in the most initial version. You can see its implementation [here](https://github.com/Mivik/prpr/blob/main/prpr/src/parse/rpe.rs). However some of its features are missing, for example `linkgroup` and `inclineEvents`, due to the lack of references. Contributions are welcome!

Currently prpr supports phigros official chart format, PEC format and RPE format. They are implemented in three files [here](https://github.com/Mivik/prpr/tree/main/prpr/src/parse) respectively.
